source "https://rubygems.org"

gem "rails", "~> 8.1.3"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "bootsnap", require: false
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Auth
gem "devise"
gem "devise-jwt"
gem "bcrypt", "~> 3.1.7"

# Authorization
gem "pundit"

# JSON serialization
gem "blueprinter"

# File uploads
gem "shrine", "~> 3.0"
gem "aws-sdk-s3", require: false
gem "image_processing", "~> 1.2"
gem "mini_magick"

# Currency
gem "money-rails", "~> 1.12"

# Background jobs
gem "sidekiq"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "bundler-audit", require: false
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "rspec-rails", "~> 7.0"
  gem "factory_bot_rails"
  gem "shoulda-matchers"
end
